name: health_care_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1
  google_fonts: ^6.3.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  http: ^1.2.0
  fl_chart: ^0.66.0
  intl: ^0.19.0

  share_plus: ^10.0.0
    # For downloading files
  dio: ^5.7.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
    # For Firebase
  dash_chat_2: ^0.0.21
    # UPDATE THIS LINE:
  google_generative_ai: ^0.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/history.png
    - assets/animation/Doctor.json