name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.2.0
        with:
          flutter-version: "3.13.0"
          channel: stable
          arch: x64

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Analyze source code
      - name: Analyze project
        run: flutter analyze

      # 5. Run Flutter tests
      - name: Run tests
        run: flutter test

      # 6. Build release APK (CD step)
      - name: Build release APK
        run: flutter build apk --release

      # 7. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: health-care-app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
